# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 079f5c5f8eb07f59d994447002ef5d1cbc9a3c8739c1a4466b4d7b451c33942c53a21a950cd46bb5f7057c4196a114f1a9b11ca68fee5891a6fb32ac2fb037fb

test:
  secret_key_base: c3d36ad1f72c6f75ee9e0ae928ce279e0b86f06bba8f3b145c4e8d127abf19f4d6b1d69cca1494ac1fa3f89fe8c23c11412c0a6715451e522514b19d5a7dd081

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
